name: Build Taxi_testing (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install pyinstaller customtkinter fpdf2 simpleeval json platform re

      - name: Build Windows executable
        shell: pwsh
        run: pyinstaller --onefile --noconsole --hidden-import customtkinter --hidden-import fpdf --hidden-import simpleeval --add-data "fonts/FreeSans/freesansbold.ttf;fonts" main.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Taxi_testing-windows
          path: dist/main.exe