name: Build Taxi_testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter

      - name: Build Windows executable
        run: pyinstaller --onefile --noconsole --hidden-import customtkinter --add-data "fonts/FreeSans/freesansbold.ttf;fonts" --icon "Icons/Taxi_1.ico" main.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Taxi_testing-windows
          path: dist/main.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter

      - name: Build Linux executable
        run: pyinstaller --onefile --noconsole --hidden-import customtkinter --add-data "fonts/FreeSans/freesansbold.ttf:fonts" main.py

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Taxi_testing-linux
          path: dist/main

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter

      - name: Build macOS executable
        run: pyinstaller --onedir --noconsole --hidden-import customtkinter --add-data "fonts/FreeSans/freesansbold.ttf:fonts" --icon "Icons/Taxi_1.icns" -y main.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: Taxi_testing-macos
          path: dist/main